# Workflow의 이름
# Workflow : 하나의 yml 파일을 하나의 Workflow라고 부른다. 
# This is the NAME of the workflow. A workflow is a single yml file!
name: Github Actions 실행시켜보기

# Event : 실행되는 시점을 설정 Event sets WHEN this workflow will be ran!
# main이라는 브랜치에 push 될 때 아래 Workflow를 실행
on:
  push: # when we git push the main branch to github it will run the following workflow
    branches:
      - main

# 하나의 Workflow는 1개 이상의 Job으로 구성된다.  One workflow consists of 1 or more 'Job'
# 여러 Job은 기본적으로 병렬적으로 수행된다. Many jobs are ran IN PARALLEL by default.
jobs: 
  # Job을 식별하기 위한 id   
  My-Deploy-Job: # this is the TITLE of the job (can be any name)
	  # Github Actions를 실행시킬 서버 종류 선택
    runs-on: ubuntu-latest # github action is a computer thus a server,
    # and we're specifying that will run on ubuntu-latest
    
    # Step : 특정 작업을 수행하는 가장 작은 단위
    # Job은 여러 Step들로 구성되어 있다.
    steps: 
      - name: Hello World 찍기 # Step에 이름 붙이는 기능 # name can be ANY name
        run: echo "Hello World" # 실행시킬 명령어 작성
        
      - name: 여러 명령어 문장 작성하기
        run: | # the | character denotes a block scalar in YAML. It indicates that the following lines are part of a multi-line string literal.
          echo "Good"
          echo "Morning"
          
			
      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

			- name: Github Actions Secret 변수 사용해보기
				run: |
					echo ${{ secrets.MY_NAME }}
					echo ${{ secrets.MY_HOBBY }}