name: Github Actions 실행시켜보기

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job: 
    runs-on: ubuntu-latest

    steps: 
      - name: Hello World 찍기
        run: echo "Hello World"
        
      - name: write multiple command line strings # using |
        run: |
          echo "Good"
          echo "Morning"

      - name: print variables natively stored in Github Actions
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

			- name: print Github Actions Secret variables
				run: |
					echo ${{ secrets.MY_NAME }}
					echo ${{ secrets.MY_HOBBY }}