name: Run Github Actions

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job: 
    runs-on: ubuntu-latest

    steps: 
      - name: print Hello World
        run: echo "Hello World"
        
      - name: write multiple command line strings
        run: |
          echo "Good"
          echo "Morning"